routes/comments.py
# comments.py
from flask import (Blueprint, session, redirect, url_for,
                   render_template, request, jsonify)
from models.general import (db, User, Comment)
from forms.web_form import ComentarForm
from utils.decorators.decorators import login_required
import locale

comments_routes = Blueprint('comments', __name__)
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')


@comments_routes.route('/escribir-comentario', methods=['GET', 'POST'])
@login_required
def comment_to_form():
    title = "Escribir comentario"
    username = session.get('username', 'NA')

    current_user = User.query.filter_by(username=username).first()
    email = current_user.email if current_user else None

    comment_form = ComentarForm(request.form)

    if request.method == 'POST' and comment_form.validate():
        comment = Comment(
            username=username,
            comment=comment_form.comment.data)

        db.session.add(comment)
        db.session.commit()

        return redirect(url_for('comments.response_web_form',
                                username=username,
                                email=email,
                                comment=comment_form.comment.data))

    else:
        return render_template('comment_user.html',
                               title=title,
                               form=comment_form,
                               username=username,
                               email=email)


@comments_routes.route('/response_web_form', methods=['GET'])
@login_required
def response_web_form():
    if request.method == 'GET':
        username = request.args.get(
            'username', 'No se ha resgitrado un usuario')
        email = request.args.get('email', 'No se ha registrado un correo')
        comment = request.args.get(
            'comment', 'No se ha registrado ningún comentario')

    return render_template('response_web_form.html',
                           title="Datos Recibidos",
                           username=username,
                           email=email,
                           comment=comment)


@comments_routes.route('/my-comments', methods=['GET'])
@login_required
def my_comments_():
    page = request.args.get('page', 1, type=int)

    username = session.get('username')

    my_comments = Comment.query.with_entities(
        Comment.comment, Comment.create_date
    ).filter_by(username=username).paginate(
        page=page, per_page=5, error_out=True)

    comments_data = []
    for comment in my_comments.items:
        comments_data.append({
            'comment': comment.comment,
            'create_date': comment.create_date.strftime(
                "%d de %B del %Y")
        })
    return jsonify({
        'comments': comments_data,
        'total_pages': my_comments.pages
    })


@comments_routes.route('/mis-comentarios', methods=['GET'])
@login_required
def show_my_comments():
    return render_template('/my-comments.html', title='Mis comentarios')


@comments_routes.route('/comentarios', methods=['GET'])
def comments():
    page = request.args.get('page', 1, type=int)

    comments = Comment.query.with_entities(
        Comment.username, Comment.comment, Comment.create_date).paginate(
        page=page, per_page=5, error_out=False)

    # Procesa los comentarios y devuelve una respuesta JSON
    comments_data = []
    for comment in comments.items:
        comments_data.append({
            'username': comment.username,
            'comment': comment.comment,
            'create_date': comment.create_date.strftime(
                "%d de %B del %Y")
        })

    return jsonify({
        'comments': comments_data,
        'total_pages': comments.pages
    })


@comments_routes.route('/comentarios-usuarios', methods=['GET'])
def show_comments():
    return render_template('comments-users.html', title='Comentarios de usuarios')

templates/_macro_web.html
{% macro renderizar(field)%}
  <td>{{ field.label}}</td>
  <dd>{{ field(**kwargs)|safe }}</dd>

  <!- Imprimir si hay errores en una lista ->
{% if field.errors %}
  <ul>
  {% for error in field.errors %}
    <li style="color: red;" >{{ error }}</li>
  {% endfor %}
  </ul>
  {% endif %} 
{% endmacro%}

templates/change_password.html
{% extends "base/web_total.html" %}
 {% block title %} {{title}} {% endblock %}
{% from "_macro_web.html" import renderizar %} 

{% block content %}
<script src="{{ url_for('static', filename='js/passwords.js') }}"></script>

<form action="" id="" method="POST">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

  <label for="current_password">Contraseña actual</label><br />
  <input type="password" name="current_password" value="" id="current_password" />
  <i class="far fa-eye" id="toggle_current_password" onclick="togglePassword('current_password')"></i>
  <br />
  <br />
  
  <label for="new_password">Contraseña nueva</label><br />
  <input type="password" name="new_password" value="" id="new_password" />
  <i class="far fa-eye" id="toggle_new_password" onclick="togglePassword('new_password')"></i>
  <br />
  <br />
  
  <label for="verify_password">Repita la contraseña</label><br />
  <input type="password" name="verify_password" value="" id="verify_password" />
  <i class="far fa-eye" id="toggle_verify_password" onclick="togglePassword('verify_password')"></i>
  <br />
  <br />
  
  <button type="submit" class="btn btn-primary">Cambiar contraseña</button>
</form>

{% endblock %}

templates/comment_user.html
{% extends 'base/web_total.html' %} {% block content %} {% from
'_macro_formularios.html' import renderizar%}

<form id="loginCookie" method="POST">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
  <!-- solo cargamos el comentario -->
  {{ renderizar(form.comment) }} {{ form.honeypot }}
  <button type="submit" class="btn btn-primary">Enviar</button>
</form>

{% endblock %}

templates/comments-users.html
{% extends 'base/web_total.html' %}
{% from '_macro_formularios.html' import renderizar %}
{% block content %}
<div class="container">
  <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>

  <!-- Pantalla de carga -->
  <div id="loading">
    <div class="loading-spinner"></div>
  </div>

  <!-- Tabla de comentarios (oculta al principio) -->
  <div id="comments-table" style="display: none;">
    <div class="table-responsive">
      <table class="table table-success table-striped">
        <thead>
          <tr>
            <th scope="col">N°</th>
            <th scope="col">Usuario</th>
            <th scope="col">Comentario</th>
            <th scope="col">Fecha</th>
          </tr>
        </thead>
        <tbody>
          <!-- Los comentarios se cargarán aquí -->
        </tbody>
      </table>
    </div>
  </div>

  <!-- Botones de paginación -->
  <div class="pagination pagination-custom" id="pagination" style="display: none;">
    <div class="pagination-buttons">
      <a id="prev-page" class="btn btn-primary">Atrás</a>
    </div>
    <div class="current-page-container">
      <span class="current-page">1</span>
    </div>
    <div class="pagination-buttons pagination-right">
      <a id="next-page" class="btn btn-primary">Siguiente</a>
    </div>
  </div>
</div>
<script>
    $(document).ready(function() {
        let currentPage = 1;
        let totalPages = null; // Variable para almacenar el número total de páginas
    
        // Función para cargar los comentarios inicialmente
        function loadInitialComments() {
            // Realiza una solicitud AJAX para cargar los comentarios de la página actual
            $.get("{{ url_for('comments.comments') }}?page=" + currentPage, function(data) {
                // Oculta la pantalla de carga después de 1 segundo
                setTimeout(function() {
                    $('#loading').hide();
    
                    // Muestra la tabla de comentarios y llena los datos
                    $('#comments-table').show();
                    $('#pagination').show();
    
                    // Llena la tabla con los comentarios
                    $('#comments-table tbody').empty();
                    $.each(data.comments, function(index, comment) {
                        let row = '<tr>';
                        row += '<td>' + ((currentPage - 1) * 5 + index + 1) + '</td>';
                        row += '<td>' + comment.username + '</td>';
                        row += '<td>' + comment.comment + '</td>';
                        row += '<td>' + comment.create_date + '</td>';
                        row += '</tr>';
                        $('#comments-table tbody').append(row);
                    });
    
                    // Actualiza el número de página actual
                    $('.current-page').text(currentPage);
    
                    // Actualiza el número total de páginas
                    totalPages = data.total_pages;
    
                    // Habilita o deshabilita los botones de paginación según sea necesario
                    if (currentPage === 1) {
                        $('#prev-page').addClass('disabled');
                    } else {
                        $('#prev-page').removeClass('disabled');
                    }
                    if (currentPage === totalPages) {
                        $('#next-page').addClass('disabled');
                    } else {
                        $('#next-page').removeClass('disabled');
                    }
                }, 1000); // 1000 milisegundos (1 segundo)
            });
        }
    
        // Carga los comentarios inicialmente al cargar la página
        loadInitialComments();
    
        // Maneja los botones de paginación
        $('#prev-page').click(function() {
            if (currentPage > 1) {
                currentPage--;
                loadComments(currentPage);
            }
        });
    
        $('#next-page').click(function() {
            if (currentPage < totalPages) {
                currentPage++;
                loadComments(currentPage);
            }
        });
    
        // Función para cargar los comentarios al cambiar de página
        function loadComments(page) {
            // Realiza una solicitud AJAX para cargar los comentarios de la página actual sin esperar
            $.get("{{ url_for('comments.comments') }}?page=" + page, function(data) {
                // Muestra la tabla con los comentarios
                $('#comments-table tbody').empty();
                $.each(data.comments, function(index, comment) {
                    let row = '<tr>';
                    row += '<td>' + ((currentPage - 1) * 5 + index + 1) + '</td>';
                    row += '<td>' + comment.username + '</td>';
                    row += '<td>' + comment.comment + '</td>';
                    row += '<td>' + comment.create_date + '</td>';
                    row += '</tr>';
                    $('#comments-table tbody').append(row);
                });
    
                // Actualiza el número de página actual
                $('.current-page').text(currentPage);
    
                // Habilita o deshabilita los botones de paginación según sea necesario
                if (currentPage === 1) {
                    $('#prev-page').addClass('disabled');
                } else {
                    $('#prev-page').removeClass('disabled');
                }
                if (currentPage === totalPages) {
                    $('#next-page').addClass('disabled');
                } else {
                    $('#next-page').removeClass('disabled');
                }
            });
        }
    });
    </script>
    
{% endblock %}

templates/cookie.html
{% extends 'base/web_total.html' %} 
{% from '_macro_formularios.html' import renderizar%}

{% block content %}

{% endblock  %}

templates/inauthorized.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Acceso no Autorizado</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/flask.ico') }}">
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap");

    * {
      padding: 0;
      margin: 0;
      box-sizing: border-box;
      font-family: "Press Start 2P";
      color: #ffffff;
      text-align: center;
    }

    body {
      background-color: #000000;
      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='42' height='58' viewBox='0 0 42 58'%3E%3Cg fill='%23dddcdd' fill-opacity='0.23'%3E%3Cpath fill-rule='evenodd' d='M12 18h12v18h6v4H18V22h-6v-4zm-6-2v-4H0V0h36v6h6v36h-6v4h6v12H6v-6H0V16h6zM34 2H2v8h24v24h8V2zM6 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM2 50h32v-8H10V18H2v32zm28-6a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm0-8a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm0-8a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm0-8a2 2 0 1 0 0 4 2 2 0 0 0 0-4z'/%3E%3C/g%3E%3C/svg%3E");
    }

    section.inauthorized {
      display: flex;
      justify-content: center;
      align-items: center;
      margin: 0 5%;
      height: 100vh;
    }

    section.inauthorized h1 {
      color: red;
      font-size: 100px;
    }

    section.inauthorized h2 {
      font-size: 50px;
    }

    section.inauthorized h1,
    h2,
    h3 {
      margin-bottom: 40px;
    }

    div.text {
      height: 50vh;
    }

    div.text a {
      text-decoration: none;
      margin-right: 20px;
    }

    div.text a:hover {
      color: red;
      text-decoration: underline;
    }

    @media only screen and (max-width: 768px) {
      section.inauthorized {
        flex-direction: column;
        justify-content: space-around;
      }
      section.inauthorized div.img img {
        width: 70vw;
        height: auto;
      }
      section.inauthorized h1 {
        font-size: 50px;
      }
      section.inauthorized h2 {
        font-size: 25px;
      }
      div.text a:active {
        color: red;
        text-decoration: underline;
      }
    }
  </style>
</head>
<body>
  <section class="inauthorized">
    
    <div class="img">
      <img src="https://assets.codepen.io/5647096/backToTheHomepage.png" alt="Regresar al inicio">
      <img src="https://assets.codepen.io/5647096/Delorean.png" alt="REX">
    </div>

    <div class="text">
      <h1>401</h1>
      <h2>Acceso no Autorizado</h2>
      <h3>¿Volver al inicio?</h3>
      <a href="/" class="yes">Si</a>
      <a href="">NO</a>
    </div>

  </section>
</body>
</html>

templates/loading.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <title>Cargando...</title>
</head>
<body>
    <div id="loading-container">
        <p id="loading-message">Cargando...</p>
    </div>
</body>
</html>

templates/login.html
{% extends 'base/formularios.html' %}
{% block title %} {{title}} {% endblock  %}

{% block content %} 
{% from '_macro_formularios.html' import renderizar%}
    
    <form action="#" id="loginForm" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        {{ renderizar(form.username) }}
        {{ renderizar(form.password) }}
        <br><br>
        <button type="submit" class="btn btn-primary" >Enviar</button>
    </form>

{% endblock  %}

templates/my-comments.html
{% extends 'base/web_total.html' %}
{% from '_macro_formularios.html' import renderizar %}
{% block content %}
<div class="container">
  <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>

  <!-- Pantalla de carga -->
  <div id="loading">
    <div class="loading-spinner"></div>
  </div>

  <div id="comments-table" style="display: none;">
    <div class="table-responsive">
      <table class="table table-success table-striped">
        <thead>
          <tr>
            <th scope="col">N°</th>
            <th scope="col">Comentario</th>
            <th scope="col">Fecha</th>
          </tr>
        </thead>
        <tbody>
          <!-- Los comentarios se cargarán aquí -->
        </tbody>
      </table>
    </div>
  </div>

  <div class="pagination pagination-custom" id="pagination" style="display: none;">
    <div class="pagination-buttons">
      <a id="prev-page" class="btn btn-primary">Atrás</a>
    </div>
    <div class="current-page-container">
      <span class="current-page">1</span>
    </div>
    <div class="pagination-buttons pagination-right">
      <a id="next-page" class="btn btn-primary">Siguiente</a>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
      let currentPage = 1;
      let totalPages = null; // Variable para almacenar el número total de páginas
  
      // Función para cargar los comentarios inicialmente
      function loadInitialComments() {
          // Realiza una solicitud AJAX para cargar los comentarios de la página actual
          $.get("{{ url_for('comments.my_comments_') }}?page=" + currentPage, function(data) {
              // Oculta la pantalla de carga después de 1 segundo
              setTimeout(function() {
                  $('#loading').hide();
  
                  // Muestra la tabla de comentarios y llena los datos
                  $('#comments-table').show();
                  $('#pagination').show();
  
                  // Llena la tabla con los comentarios
                  $('#comments-table tbody').empty();
                  $.each(data.comments, function(index, comment) {
                      let row = '<tr>';
                      row += '<td>' + ((currentPage - 1) * 5 + index + 1) + '</td>';
                      row += '<td>' + comment.comment + '</td>';
                      row += '<td>' + comment.create_date + '</td>';
                      row += '</tr>';
                      $('#comments-table tbody').append(row);
                  });
  
                  // Actualiza el número de página actual
                  $('.current-page').text(currentPage);
  
                  // Actualiza el número total de páginas
                  totalPages = data.total_pages;
  
                  // Habilita o deshabilita los botones de paginación según sea necesario
                  if (currentPage === 1) {
                      $('#prev-page').addClass('disabled');
                  } else {
                      $('#prev-page').removeClass('disabled');
                  }
                  if (currentPage === totalPages) {
                      $('#next-page').addClass('disabled');
                  } else {
                      $('#next-page').removeClass('disabled');
                  }
              }, 1000); // 1000 milisegundos (1 segundo)
          });
      }
  
      // Carga los comentarios inicialmente al cargar la página
      loadInitialComments();
  
      // Maneja los botones de paginación
      $('#prev-page').click(function() {
          if (currentPage > 1) {
              currentPage--;
              loadComments(currentPage);
          }
      });
  
      $('#next-page').click(function() {
          if (currentPage < totalPages) {
              currentPage++;
              loadComments(currentPage);
          }
      });
  
      // Función para cargar los comentarios al cambiar de página
      function loadComments(page) {
          // Realiza una solicitud AJAX para cargar los comentarios de la página actual sin esperar
          $.get("{{ url_for('comments.my_comments_') }}?page=" + page, function(data) {
              // Muestra la tabla con los comentarios
              $('#comments-table tbody').empty();
              $.each(data.comments, function(index, comment) {
                  let row = '<tr>';
                  row += '<td>' + ((currentPage - 1) * 5 + index + 1) + '</td>';
                  row += '<td>' + comment.comment + '</td>';
                  row += '<td>' + comment.create_date + '</td>';
                  row += '</tr>';
                  $('#comments-table tbody').append(row);
              });
  
              // Actualiza el número de página actual
              $('.current-page').text(currentPage);
  
              // Habilita o deshabilita los botones de paginación según sea necesario
              if (currentPage === 1) {
                  $('#prev-page').addClass('disabled');
              } else {
                  $('#prev-page').removeClass('disabled');
              }
              if (currentPage === totalPages) {
                  $('#next-page').addClass('disabled');
              } else {
                  $('#next-page').removeClass('disabled');
              }
          });
      }
  });
  </script>
{% endblock %}

templates/notfound.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Not Found 404</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/flask.ico') }}">

  <style>
    @import url("https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap");

    * {
      padding: 0;
      margin: 0;
      box-sizing: border-box;
      font-family: "Press Start 2P";
      color: #ffffff;
      text-align: center;
    }

    body {
      background-color: #000000;
      background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='42' height='58' viewBox='0 0 42 58'%3E%3Cg fill='%23dddcdd' fill-opacity='0.23'%3E%3Cpath fill-rule='evenodd' d='M12 18h12v18h6v4H18V22h-6v-4zm-6-2v-4H0V0h36v6h6v36h-6v4h6v12H6v-6H0V16h6zM34 2H2v8h24v24h8V2zM6 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm8 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4zM2 50h32v-8H10V18H2v32zm28-6a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-8 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm0-8a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm0-8a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm0-8a2 2 0 1 0 0 4 2 2 0 0 0 0-4z'/%3E%3C/g%3E%3C/svg%3E");
    }

    section.notFound {
      display: flex;
      justify-content: center;
      align-items: center;
      margin: 0 5%;
      height: 100vh;
    }

    section.notFound h1 {
      color: red;
      font-size: 100px;
    }

    section.notFound h2 {
      font-size: 50px;
    }

    section.notFound h1,
    h2,
    h3 {
      margin-bottom: 40px;
    }

    div.text {
      height: 50vh;
    }

    div.text a {
      text-decoration: none;
      margin-right: 20px;
    }

    div.text a:hover {
      color: red;
      text-decoration: underline;
    }

    @media only screen and (max-width: 768px) {
      section.notFound {
        flex-direction: column;
        justify-content: space-around;
      }
      section.notFound div.img img {
        width: 70vw;
        height: auto;
      }
      section.notFound h1 {
        font-size: 50px;
      }
      section.notFound h2 {
        font-size: 25px;
      }
      div.text a:active {
        color: red;
        text-decoration: underline;
      }
    }
  </style>

</head>
<body>
  
  <section class="notFound">
    <div class="img">
      <img src="https://assets.codepen.io/5647096/backToTheHomepage.png" alt="Regresar al inicio">
      <img src="https://assets.codepen.io/5647096/Delorean.png" alt="REX">
    </div>

    <div class="text">
      <h1>404</h1>
      <h2>Página no encontrada</h2>
      <h3>¿Volver atrás?</h3>
      <a href="/" class="yes">Si</a>
      <a href="">NO</a>
    </div>
  </section>

</body>
</html>

templates/reset_password.html
{% extends 'base/web_total.html' %} {% block title %} {{title}} {% endblock %}
{% block content %}
<style>
  @media only screen and (max-width: 768px) {
    form {
      width: 80%;
      margin: 0 auto;
    }
  }
</style>

<form action="" id="" method="POST">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

  <label for="username">Usuario</label><br>
  <input type="text" name="username" value="" />
    <br> <br>
  <button type="submit" class="btn btn-primary">Restablecer contraseña</button>
</form>

{% endblock %}

templates/response_databases.html
{% extends 'base/base.html' %} 
{% block content %}
<div class="alert alert-success" role="alert">
  <h3>Usuario registrado</h3>
  <label>Usuario: <strong>{{ username }}</strong></label>
  <br />
  <label>Correo: <strong>{{ email }}</strong></label>
  <br />
  <a href="/ingresar">Ya puede iniciar sesion</a>
  
  <script>
    Swal.fire(
      "Usuario registrado",
      "Usuario: {{ username }}<br>Correo: {{ email }}",
      "success"
    );
  </script>
</div>

{% endblock %}

templates/response_registers.html
{% extends 'base/base.html' %} 

{% block content %}
<div class="alert alert-success" role="alert">
  <h3>Datos registrados</h3>
    
  <a href="/">Ir al inicio</a>
  
  <script>
    Swal.fire(
      "Datos registrados!",
      "Registro exitoso",
      "success"
    );
  </script>
</div>

{% endblock %}

templates/web_total.html
{% extends 'base/web_total.html' %}
{% block title %} {{title}} {% endblock  %}

{% block content %} 
{% from '_macro_web.html' import renderizar with context%}

{% endblock  %}

{% block flask %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <img src="{{ url_for('static', filename='img/flask.jpg') }}" alt="" class="img-fluid mx-auto d-block">
      </div>
    </div>
  </div>
{% endblock  %}